// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL8c2M9AYXQ1GlyJjzhIL3NXGQE-KEuN0',
    appId: '1:312649231657:web:85d38de5e716c68caf5b38',
    messagingSenderId: '312649231657',
    projectId: 'bim324-192d4',
    authDomain: 'bim324-192d4.firebaseapp.com',
    storageBucket: 'bim324-192d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAZFzMz75iMxTGNlCp-F4zj1gnzMPPkkQ',
    appId: '1:312649231657:android:5e2c25c32a4bb308af5b38',
    messagingSenderId: '312649231657',
    projectId: 'bim324-192d4',
    storageBucket: 'bim324-192d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoSA3Nl7MhusEtGf5q-xnJjX0w9QCiqt8',
    appId: '1:312649231657:ios:19a8cf6da2ec6575af5b38',
    messagingSenderId: '312649231657',
    projectId: 'bim324-192d4',
    storageBucket: 'bim324-192d4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoSA3Nl7MhusEtGf5q-xnJjX0w9QCiqt8',
    appId: '1:312649231657:ios:19a8cf6da2ec6575af5b38',
    messagingSenderId: '312649231657',
    projectId: 'bim324-192d4',
    storageBucket: 'bim324-192d4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL8c2M9AYXQ1GlyJjzhIL3NXGQE-KEuN0',
    appId: '1:312649231657:web:f96ecec6dee3752caf5b38',
    messagingSenderId: '312649231657',
    projectId: 'bim324-192d4',
    authDomain: 'bim324-192d4.firebaseapp.com',
    storageBucket: 'bim324-192d4.firebasestorage.app',
  );
}
